# Generated by Django 2.2 on 2021-01-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
