# Generated by Django 2.2 on 2021-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
